Update scrape_kangur.yml

diff --git a/.github/workflows/scrape_kangur.yml b/.github/workflows/scrape_kangur.yml
--- a/.github/workflows/scrape_kangur.yml
+++ b/.github/workflows/scrape_kangur.yml
@@ -23,9 +23,15 @@ jobs:
         AVAILABLE_END='</span>'
         raw_website=$(curl -l $URL)
         current_date=$(date +"%Y-%m-%d %H:%M")
-        sell_price=$(echo $raw_website | grep -oP "(?<=${SELL_START}).*?(?=${SELL_END})" | cut -d">" -f2 | cut -d" " -f1 | tr , .  || echo "error pattern")
-        buy_price=$(echo $raw_website | grep -oP "(?<=${BUY_START}).*?(?=${BUY_END})" | cut -d">" -f2 | cut -d" " -f1 | tr , .  || echo "error pattern")
-        available=$(echo $raw_website | grep -oP "(?<=${AVAILABLE_START}).*?(?=${AVAILABLE_END})" || echo "dostępny")
+        if [ -z "$raw_website" ]; then
+          sell_price=""
+          buy_price=""
+          available="strona niedostępna"
+        else
+          sell_price=$(echo $raw_website | grep -oP "(?<=${SELL_START}).*?(?=${SELL_END})" | cut -d">" -f2 | cut -d" " -f1 | tr , .  || echo "error pattern")
+          buy_price=$(echo $raw_website | grep -oP "(?<=${BUY_START}).*?(?=${BUY_END})" | cut -d">" -f2 | cut -d" " -f1 | tr , .  || echo "error pattern")
+          available=$(echo $raw_website | grep -oP "(?<=${AVAILABLE_START}).*?(?=${AVAILABLE_END})" || echo "dostępny")
+        fi
         echo "${current_date},${sell_price},${buy_price},${available}" >> gold_scrapper_kangur.csv
     - name: Commit and push if it changed
       run: |-
